# Generated by Django 4.2.3 on 2023-07-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(blank=True, default=None, null=True)),
                ('text', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
